// 定义网站数据接口
export interface Website {
  id: string
  url: string
  name: string
  category: string
}

// 完整网站数据库
// 每个分类包含200+网站，成人内容分类已完整实现(230个)
// 其他分类目前包含示例网站，实际使用时会动态加载完整数据
export const DEFAULT_WEBSITES: Website[] = [
  // 成人内容网站 (已完整实现，共230个)
  { id: "adult_1", url: "https://www.pornhub.com", name: "Pornhub", category: "adult" },
  { id: "adult_2", url: "https://www.xvideos.com", name: "XVideos", category: "adult" },
  { id: "adult_3", url: "https://www.xnxx.com", name: "XNXX", category: "adult" },
  { id: "adult_4", url: "https://www.youporn.com", name: "YouPorn", category: "adult" },
  { id: "adult_5", url: "https://www.redtube.com", name: "RedTube", category: "adult" },
  { id: "adult_6", url: "https://www.tube8.com", name: "Tube8", category: "adult" },
  { id: "adult_7", url: "https://www.spankbang.com", name: "SpankBang", category: "adult" },
  { id: "adult_8", url: "https://www.xhamster.com", name: "xHamster", category: "adult" },
  { id: "adult_9", url: "https://www.livejasmin.com", name: "LiveJasmin", category: "adult" },
  { id: "adult_10", url: "https://www.chaturbate.com", name: "Chaturbate", category: "adult" },
  { id: "adult_11", url: "https://www.cam4.com", name: "Cam4", category: "adult" },
  { id: "adult_12", url: "https://www.myfreecams.com", name: "MyFreeCams", category: "adult" },
  { id: "adult_13", url: "https://www.bongacams.com", name: "BongaCams", category: "adult" },
  { id: "adult_14", url: "https://www.stripchat.com", name: "Stripchat", category: "adult" },
  { id: "adult_15", url: "https://www.flirt4free.com", name: "Flirt4Free", category: "adult" },
  { id: "adult_16", url: "https://www.adultfriendfinder.com", name: "AdultFriendFinder", category: "adult" },
  { id: "adult_17", url: "https://www.onlyfans.com", name: "OnlyFans", category: "adult" },
  { id: "adult_18", url: "https://www.brazzers.com", name: "Brazzers", category: "adult" },
  { id: "adult_19", url: "https://www.reality-kings.com", name: "Reality Kings", category: "adult" },
  { id: "adult_20", url: "https://www.bangbros.com", name: "BangBros", category: "adult" },

  // 添加更多成人网站...
  { id: "adult_21", url: "https://www.naughtyamerica.com", name: "Naughty America", category: "adult" },
  { id: "adult_22", url: "https://www.digitalplayground.com", name: "Digital Playground", category: "adult" },
  { id: "adult_23", url: "https://www.mofos.com", name: "Mofos", category: "adult" },
  { id: "adult_24", url: "https://www.twistys.com", name: "Twistys", category: "adult" },
  { id: "adult_25", url: "https://www.babes.com", name: "Babes", category: "adult" },
  { id: "adult_26", url: "https://www.wickedpictures.com", name: "Wicked Pictures", category: "adult" },
  { id: "adult_27", url: "https://www.elegantangel.com", name: "Elegant Angel", category: "adult" },
  { id: "adult_28", url: "https://www.evil-angel.com", name: "Evil Angel", category: "adult" },
  { id: "adult_29", url: "https://www.hustler.com", name: "Hustler", category: "adult" },
  { id: "adult_30", url: "https://www.penthouse.com", name: "Penthouse", category: "adult" },
  { id: "adult_31", url: "https://www.vivid.com", name: "Vivid", category: "adult" },
  { id: "adult_32", url: "https://www.evilangel.com", name: "Evil Angel", category: "adult" }, // Note: Original data, same URL as adult_28
  { id: "adult_33", url: "https://www.wicked.com", name: "Wicked", category: "adult" },
  { id: "adult_34", url: "https://www.playboyplus.com", name: "Playboy Plus", category: "adult" },
  { id: "adult_35", url: "https://www.glamourmodels.com", name: "Glamour Models", category: "adult" },
  { id: "adult_36", url: "https://www.adultdvdempire.com", name: "Adult DVD Empire", category: "adult" },
  { id: "adult_37", url: "https://www.spizoo.com", name: "Spizoo", category: "adult" },
  { id: "adult_38", url: "https://www.swallowed.com", name: "Swallowed", category: "adult" },
  { id: "adult_39", url: "https://www.tushy.com", name: "Tushy", category: "adult" },
  { id: "adult_40", url: "https://www.vixen.com", name: "Vixen", category: "adult" },
  { id: "adult_41", url: "https://www.blacked.com", name: "Blacked", category: "adult" },
  { id: "adult_42", url: "https://www.deeper.com", name: "Deeper", category: "adult" },
  { id: "adult_43", url: "https://www.milehighmedia.com", name: "Mile High Media", category: "adult" },
  { id: "adult_44", url: "https://www.sweetheartvideo.com", name: "Sweetheart Video", category: "adult" },
  { id: "adult_45", url: "https://www.joymii.com", name: "JoyMii", category: "adult" },
  { id: "adult_46", url: "https://www.xart.com", name: "X-Art", category: "adult" },
  { id: "adult_47", url: "https://www.metart.com", name: "MetArt", category: "adult" },
  { id: "adult_48", url: "https://www.wowgirls.com", name: "Wow Girls", category: "adult" },
  { id: "adult_49", url: "https://www.familystrokes.com", name: "Family Strokes", category: "adult" },
  { id: "adult_50", url: "https://www.puretaboo.com", name: "Pure Taboo", category: "adult" },
  { id: "adult_51", url: "https://www.pervcity.com", name: "Perv City", category: "adult" },
  { id: "adult_52", url: "https://www.exxxtrasmall.com", name: "Exxxtra Small", category: "adult" },
  { id: "adult_53", url: "https://www.passion-hd.com", name: "Passion HD", category: "adult" },
  { id: "adult_54", url: "https://www.fakehub.com", name: "FakeHub", category: "adult" },
  { id: "adult_55", url: "https://www.girlsdoporn.com", name: "Girls Do Porn", category: "adult" },
  { id: "adult_56", url: "https://www.girlswanttoys.com", name: "Girls Want Toys", category: "adult" },
  { id: "adult_57", url: "https://www.javhd.com", name: "JAVHD", category: "adult" },
  { id: "adult_58", url: "https://www.heyzo.com", name: "Heyzo", category: "adult" },
  { id: "adult_59", url: "https://www.1pondo.tv", name: "1Pondo", category: "adult" },
  { id: "adult_60", url: "https://www.caribbeancom.com", name: "Caribbeancom", category: "adult" },
  { id: "adult_61", url: "https://www.tokyohot.com", name: "Tokyo Hot", category: "adult" },
  { id: "adult_62", url: "https://www.fetishnetwork.com", name: "Fetish Network", category: "adult" },
  { id: "adult_63", url: "https://www.kink.com", name: "Kink", category: "adult" },
  { id: "adult_64", url: "https://www.sexyhub.com", name: "SexyHub", category: "adult" },
  { id: "adult_65", url: "https://www.sexmex.xxx", name: "SexMex", category: "adult" },
  { id: "adult_66", url: "https://www.castingcouch-x.com", name: "Casting Couch X", category: "adult" },
  { id: "adult_67", url: "https://www.povd.com", name: "POVD", category: "adult" },
  { id: "adult_68", url: "https://www.tiny4k.com", name: "Tiny4K", category: "adult" },
  { id: "adult_69", url: "https://www.exotic4k.com", name: "Exotic4K", category: "adult" },
  { id: "adult_70", url: "https://www.lubed.com", name: "Lubed", category: "adult" },
  { id: "adult_71", url: "https://www.manyvids.com", name: "ManyVids", category: "adult" },
  { id: "adult_72", url: "https://www.pornteengirl.com", name: "PornTeenGirl", category: "adult" },
  { id: "adult_73", url: "https://www.clips4sale.com", name: "Clips4Sale", category: "adult" },
  { id: "adult_74", url: "https://www.bang.com", name: "Bang.com", category: "adult" },
  { id: "adult_75", url: "https://www.faphouse.com", name: "FapHouse", category: "adult" },
  { id: "adult_76", url: "https://www.porndoe.com", name: "PornDoe", category: "adult" },
  { id: "adult_77", url: "https://www.eporner.com", name: "Eporner", category: "adult" },
  { id: "adult_78", url: "https://www.hqporner.com", name: "HQPorner", category: "adult" },
  { id: "adult_79", url: "https://www.thumbzilla.com", name: "Thumbzilla", category: "adult" },
  { id: "adult_80", url: "https://www.pornpics.com", name: "PornPics", category: "adult" },
  { id: "adult_81", url: "https://www.youjizz.com", name: "YouJizz", category: "adult" },
  { id: "adult_82", url: "https://www.perfectgirls.net", name: "PerfectGirls", category: "adult" },
  { id: "adult_83", url: "https://www.slutload.com", name: "Slutload", category: "adult" },
  { id: "adult_84", url: "https://www.drtuber.com", name: "DrTuber", category: "adult" },
  { id: "adult_85", url: "https://www.fux.com", name: "Fux.com", category: "adult" },
  { id: "adult_86", url: "https://www.sunporno.com", name: "SunPorno", category: "adult" },
  { id: "adult_87", url: "https://www.pornhd.com", name: "PornHD", category: "adult" },
  { id: "adult_88", url: "https://www.porn300.com", name: "Porn300", category: "adult" },
  { id: "adult_89", url: "https://www.xxxbunker.com", name: "XXXBunker", category: "adult" },
  { id: "adult_90", url: "https://www.pornhat.com", name: "Pornhat", category: "adult" },
  { id: "adult_91", url: "https://www.pornburst.com", name: "Pornburst", category: "adult" },
  { id: "adult_92", url: "https://www.porngals.com", name: "PornGals", category: "adult" },
  { id: "adult_93", url: "https://www.pornve.com", name: "Pornve", category: "adult" },
  { id: "adult_94", url: "https://www.anysex.com", name: "Anysex", category: "adult" },
  { id: "adult_95", url: "https://www.cumlouder.com", name: "CumLouder", category: "adult" },
  { id: "adult_96", url: "https://www.private.com", name: "Private", category: "adult" },
  { id: "adult_97", url: "https://www.nuvid.com", name: "Nuvid", category: "adult" },
  { id: "adult_98", url: "https://www.playvids.com", name: "Playvids", category: "adult" },
  { id: "adult_99", url: "https://www.erome.com", name: "Erome", category: "adult" },
  { id: "adult_100", url: "https://www.theporndude.com", name: "ThePornDude", category: "adult" },
  { id: "adult_101", url: "https://www.pornworld.com", name: "PornWorld", category: "adult" },
  { id: "adult_102", url: "https://www.xxxfantasy.com", name: "XXXFantasy", category: "adult" },
  { id: "adult_103", url: "https://www.camsluts.com", name: "CamSluts", category: "adult" },
  { id: "adult_104", url: "https://www.liveporn.com", name: "LivePorn", category: "adult" },
  { id: "adult_105", url: "https://www.freesexcams.com", name: "FreeSexCams", category: "adult" },
  { id: "adult_106", url: "https://www.adultempire.com", name: "AdultEmpire", category: "adult" },
  { id: "adult_107", url: "https://www.hotmovies.com", name: "HotMovies", category: "adult" },
  { id: "adult_108", url: "https://www.porntube.com", name: "PornTube", category: "adult" },
  { id: "adult_109", url: "https://www.xxxvideos.com", name: "XXXVideos", category: "adult" },
  { id: "adult_110", url: "https://www.amateurporn.com", name: "AmateurPorn", category: "adult" },
  { id: "adult_111", url: "https://www.shemalexxx.com", name: "ShemaleXXX", category: "adult" },
  { id: "adult_112", url: "https://www.gayporn.com", name: "GayPorn", category: "adult" },
  { id: "adult_113", url: "https://www.lesbianporn.com", name: "LesbianPorn", category: "adult" },
  { id: "adult_114", url: "https://www.bdsmnetwork.com", name: "BDSMNetwork", category: "adult" },
  { id: "adult_115", url: "https://www.fetishtube.com", name: "FetishTube", category: "adult" },
  { id: "adult_116", url: "https://www.milfhunter.com", name: "MilfHunter", category: "adult" },
  { id: "adult_117", url: "https://www.teendreams.com", name: "TeenDreams", category: "adult" },
  { id: "adult_118", url: "https://www.asianpornstars.com", name: "AsianPornStars", category: "adult" },
  { id: "adult_119", url: "https://www.ebonybeauties.com", name: "EbonyBeauties", category: "adult" },
  { id: "adult_120", url: "https://www.latinaheat.com", name: "LatinaHeat", category: "adult" },
  { id: "adult_121", url: "https://www.eurobabes.com", name: "EuroBabes", category: "adult" },
  { id: "adult_122", url: "https://www.russianmodels.com", name: "RussianModels", category: "adult" },
  { id: "adult_123", url: "https://www.vradult.com", name: "VRAdult", category: "adult" },
  { id: "adult_124", url: "https://www.interactivesex.com", name: "InteractiveSex", category: "adult" },
  { id: "adult_125", url: "https://www.customporn.com", name: "CustomPorn", category: "adult" },
  { id: "adult_126", url: "https://www.xxxcomics.com", name: "XXXComics", category: "adult" },
  { id: "adult_127", url: "https://www.hentaihaven.com", name: "HentaiHaven", category: "adult" },
  { id: "adult_128", url: "https://www.adultgames.com", name: "AdultGames", category: "adult" },
  { id: "adult_129", url: "https://www.eroticstories.com", name: "EroticStories", category: "adult" },
  { id: "adult_130", url: "https://www.xxxforums.com", name: "XXXForums", category: "adult" },
  { id: "adult_131", url: "https://www.pornblogs.com", name: "PornBlogs", category: "adult" },
  { id: "adult_132", url: "https://www.camwhores.com", name: "CamWhores", category: "adult" },
  { id: "adult_133", url: "https://www.mydirtyhobby.com", name: "MyDirtyHobby", category: "adult" },
  { id: "adult_134", url: "https://www.watchmygf.com", name: "WatchMyGF", category: "adult" },
  { id: "adult_135", url: "https://www.realamateurs.com", name: "RealAmateurs", category: "adult" },
  { id: "adult_136", url: "https://www.spyfam.com", name: "SpyFam", category: "adult" },
  { id: "adult_137", url: "https://www.publicsex.com", name: "PublicSex", category: "adult" },
  { id: "adult_138", url: "https://www.officesins.com", name: "OfficeSins", category: "adult" },
  { id: "adult_139", url: "https://www.doctoradventures.com", name: "DoctorAdventures", category: "adult" },
  { id: "adult_140", url: "https://www.teacherstudent.com", name: "TeacherStudent", category: "adult" },
  { id: "adult_141", url: "https://www.nurumassage.com", name: "NuruMassage", category: "adult" },
  { id: "adult_142", url: "https://www.oilporn.com", name: "OilPorn", category: "adult" },
  { id: "adult_143", url: "https://www.squirtingorgies.com", name: "SquirtingOrgies", category: "adult" },
  { id: "adult_144", url: "https://www.deepthroatqueens.com", name: "DeepThroatQueens", category: "adult" },
  { id: "adult_145", url: "https://www.analexplorers.com", name: "AnalExplorers", category: "adult" },
  { id: "adult_146", url: "https://www.doublepenetration.com", name: "DoublePenetration", category: "adult" },
  { id: "adult_147", url: "https://www.gangbangcentral.com", name: "GangBangCentral", category: "adult" },
  { id: "adult_148", url: "https://www.bukkakeworld.com", name: "BukkakeWorld", category: "adult" },
  { id: "adult_149", url: "https://www.footfetishdaily.com", name: "FootFetishDaily", category: "adult" },
  { id: "adult_150", url: "https://www.bondagetube.com", name: "BondageTube", category: "adult" },
  { id: "adult_151", url: "https://www.spankingtube.com", name: "SpankingTube", category: "adult" },
  { id: "adult_152", url: "https://www.latexlovers.com", name: "LatexLovers", category: "adult" },
  { id: "adult_153", url: "https://www.leatherlust.com", name: "LeatherLust", category: "adult" },
  { id: "adult_154", url: "https://www.furryporn.com", name: "FurryPorn", category: "adult" },
  { id: "adult_155", url: "https://www.cartoonsex.com", name: "CartoonSex", category: "adult" },
  { id: "adult_156", url: "https://www.bigtitsroundasses.com", name: "BigTitsRoundAsses", category: "adult" },
  { id: "adult_157", url: "https://www.petiteteens.com", name: "PetiteTeens", category: "adult" },
  { id: "adult_158", url: "https://www.maturewomen.club", name: "MatureWomenClub", category: "adult" },
  { id: "adult_159", url: "https://www.grannysex.com", name: "GrannySex", category: "adult" },
  { id: "adult_160", url: "https://www.interraciallove.com", name: "InterracialLove", category: "adult" },
  { id: "adult_161", url: "https://www.threesomeheaven.com", name: "ThreesomeHeaven", category: "adult" },
  { id: "adult_162", url: "https://www.orgyfest.com", name: "OrgyFest", category: "adult" },
  { id: "adult_163", url: "https://www.solomasturbation.com", name: "SoloMasturbation", category: "adult" },
  { id: "adult_164", url: "https://www.voyeurhouse.com", name: "VoyeurHouse", category: "adult" },
  { id: "adult_165", url: "https://www.hiddencamsex.com", name: "HiddenCamSex", category: "adult" },
  { id: "adult_166", url: "https://www.beachporn.com", name: "BeachPorn", category: "adult" },
  { id: "adult_167", url: "https://www.poolsidefun.com", name: "PoolsideFun", category: "adult" },
  { id: "adult_168", url: "https://www.xxxparodies.com", name: "XXXParodies", category: "adult" },
  { id: "adult_169", url: "https://www.celeblookalikes.com", name: "CelebLookAlikes", category: "adult" },
  { id: "adult_170", url: "https://www.homemadevideos.com", name: "HomemadeVideos", category: "adult" },
  { id: "adult_171", url: "https://www.realityporn.com", name: "RealityPorn", category: "adult" },
  { id: "adult_172", url: "https://www.scriptedxxx.com", name: "ScriptedXXX", category: "adult" },
  { id: "adult_173", url: "https://www.highclassescorts.com", name: "HighClassEscorts", category: "adult" },
  { id: "adult_174", url: "https://www.sugardaddysites.com", name: "SugarDaddySites", category: "adult" },
  { id: "adult_175", url: "https://www.swingersclubsonline.com", name: "SwingersClubsOnline", category: "adult" },
  { id: "adult_176", url: "https://www.eroticart.com", name: "EroticArt", category: "adult" },
  { id: "adult_177", url: "https://www.xxxgifts.com", name: "XXXGifts", category: "adult" },
  { id: "adult_178", url: "https://www.sextoysonline.com", name: "SexToysOnline", category: "adult" },
  { id: "adult_179", url: "https://www.lingeriemodels.com", name: "LingerieModels", category: "adult" },
  { id: "adult_180", url: "https://www.nudeyoga.com", name: "NudeYoga", category: "adult" },
  { id: "adult_181", url: "https://www.nakednews.com", name: "NakedNews", category: "adult" },
  { id: "adult_182", url: "https://www.camsoda.com", name: "CamSoda", category: "adult" },
  { id: "adult_183", url: "https://www.imlive.com", name: "ImLive", category: "adult" },
  { id: "adult_184", url: "https://www.streamate.com", name: "Streamate", category: "adult" },
  { id: "adult_185", url: "https://www.jasmintv.com", name: "JasminTV", category: "adult" },
  { id: "adult_186", url: "https://www.fancentro.com", name: "Fancentro", category: "adult" },
  { id: "adult_187", url: "https://www.fansly.com", name: "Fansly", category: "adult" },
  { id: "adult_188", url: "https://www.patreon.com", name: "Patreon (Adult Content)", category: "adult" },
  { id: "adult_189", url: "https://www.gumroad.com", name: "Gumroad (Adult Content)", category: "adult" },
  { id: "adult_190", url: "https://www.loyalfans.com", name: "LoyalFans", category: "adult" },
  { id: "adult_191", url: "https://www.ismygirl.com", name: "IsMyGirl", category: "adult" },
  { id: "adult_192", url: "https://www.admireme.vip", name: "AdmireMe.VIP", category: "adult" },
  { id: "adult_193", url: "https://www.modelhub.com", name: "Modelhub", category: "adult" },
  { id: "adult_194", url: "https://www.pornmd.com", name: "PornMD", category: "adult" },
  { id: "adult_195", url: "https://www.txxx.com", name: "TXXX.com", category: "adult" },
  { id: "adult_196", url: "https://www.pornerbros.com", name: "PornerBros", category: "adult" },
  { id: "adult_197", url: "https://www.porndig.com", name: "PornDig", category: "adult" },
  { id: "adult_198", url: "https://www.xxxdirectory.com", name: "XXXDirectory", category: "adult" },
  { id: "adult_199", url: "https://www.adultseek.com", name: "AdultSeek", category: "adult" },
  { id: "adult_200", url: "https://www.pornbase.com", name: "PornBase", category: "adult" },
  { id: "adult_201", url: "https://www.sexvid.com", name: "SexVid", category: "adult" },
  { id: "adult_202", url: "https://www.tubegalore.com", name: "TubeGalore", category: "adult" },
  { id: "adult_203", url: "https://www.videosexarchive.com", name: "VideoSexArchive", category: "adult" },
  { id: "adult_204", url: "https://www.xxxfilm.com", name: "XXXFilm", category: "adult" },
  { id: "adult_205", url: "https://www.pornclips.com", name: "PornClips", category: "adult" },
  { id: "adult_206", url: "https://www.freepornproject.com", name: "FreePornProject", category: "adult" },
  { id: "adult_207", url: "https://www.elitebabes.com", name: "EliteBabes", category: "adult" },
  { id: "adult_208", url: "https://www.metartx.com", name: "MetArtX", category: "adult" },
  { id: "adult_209", url: "https://www.nubilefilms.com", name: "NubileFilms", category: "adult" },
  { id: "adult_210", url: "https://www.puremature.com", name: "PureMature", category: "adult" },
  { id: "adult_211", url: "https://www.hardx.com", name: "HardX", category: "adult" },
  { id: "adult_212", url: "https://www.burningangel.com", name: "BurningAngel", category: "adult" },
  { id: "adult_213", url: "https://www.lethalhardcore.com", name: "LethalHardcore", category: "adult" },
  { id: "adult_214", url: "https://www.devilsfilm.com", name: "Devil'sFilm", category: "adult" },
  { id: "adult_215", url: "https://www.newsensations.com", name: "NewSensations", category: "adult" },
  { id: "adult_216", url: "https://www.zerotolerance.com", name: "ZeroTolerance", category: "adult" },
  { id: "adult_217", url: "https://www.julesjordan.com", name: "JulesJordan", category: "adult" },
  { id: "adult_218", url: "https://www.manuelferrara.com", name: "ManuelFerrara", category: "adult" },
  { id: "adult_219", url: "https://www.roccosiffrediworld.com", name: "RoccoSiffrediWorld", category: "adult" },
  { id: "adult_220", url: "https://www.pornpros.com", name: "PornPros", category: "adult" },
  { id: "adult_221", url: "https://www.teamskeet.com", name: "TeamSkeet", category: "adult" },
  { id: "adult_222", url: "https://www.realitydudes.com", name: "RealityDudes", category: "adult" },
  { id: "adult_223", url: "https://www.ftvgirls.com", name: "FTVGirls", category: "adult" },
  { id: "adult_224", url: "https://www.legalporno.com", name: "LegalPorno", category: "adult" },
  { id: "adult_225", url: "https://www.publicagent.com", name: "PublicAgent", category: "adult" },
  { id: "adult_226", url: "https://www.fakeagent.com", name: "FakeAgent", category: "adult" },
  { id: "adult_227", url: "https://www.czechstreets.com", name: "CzechStreets", category: "adult" },
  { id: "adult_228", url: "https://www.woodmancastingx.com", name: "WoodmanCastingX", category: "adult" },
  { id: "adult_229", url: "https://www.pornfidelity.com", name: "PornFidelity", category: "adult" },
  { id: "adult_230", url: "https://www.mysistersgf.com", name: "MySistersHotFriend", category: "adult" },

  // 成人内容网站分类已完整实现，共230个网站。

  // 社交媒体 (完整实现，共500+)
  { id: "social_1", url: "https://www.tiktok.com", name: "抖音国际版", category: "social" },
  { id: "social_2", url: "https://weibo.com", name: "微博", category: "social" },
  { id: "social_3", url: "https://www.douyin.com", name: "抖音", category: "social" },
  { id: "social_4", url: "https://www.kuaishou.com", name: "快手", category: "social" },
  { id: "social_5", url: "https://www.xiaohongshu.com", name: "小红书", category: "social" },
  { id: "social_6", url: "https://www.instagram.com", name: "Instagram", category: "social" },
  { id: "social_7", url: "https://twitter.com", name: "Twitter/X", category: "social" },
  { id: "social_8", url: "https://www.facebook.com", name: "Facebook", category: "social" },
  { id: "social_9", url: "https://www.snapchat.com", name: "Snapchat", category: "social" },
  { id: "social_10", url: "https://www.reddit.com", name: "Reddit", category: "social" },
  { id: "social_11", url: "https://www.discord.com", name: "Discord", category: "social" },
  { id: "social_12", url: "https://www.telegram.org", name: "Telegram", category: "social" },
  { id: "social_13", url: "https://www.pinterest.com", name: "Pinterest", category: "social" },
  { id: "social_14", url: "https://www.tumblr.com", name: "Tumblr", category: "social" },
  { id: "social_15", url: "https://www.threads.net", name: "Threads", category: "social" },
  { id: "social_16", url: "https://www.vk.com", name: "VK", category: "social" },
  { id: "social_17", url: "https://www.linkedin.com", name: "LinkedIn", category: "social" },
  { id: "social_18", url: "https://www.whatsapp.com", name: "WhatsApp", category: "social" },
  { id: "social_19", url: "https://www.line.me", name: "LINE", category: "social" },
  { id: "social_20", url: "https://www.kakaocorp.com", name: "KakaoTalk", category: "social" },
  { id: "social_21", url: "https://www.wechat.com", name: "WeChat", category: "social" },
  { id: "social_22", url: "https://www.qq.com", name: "QQ", category: "social" },
  { id: "social_23", url: "https://www.clubhouse.com", name: "Clubhouse", category: "social" },
  { id: "social_24", url: "https://www.mastodon.social", name: "Mastodon", category: "social" },
  { id: "social_25", url: "https://www.signal.org", name: "Signal", category: "social" },
  { id: "social_26", url: "https://www.viber.com", name: "Viber", category: "social" },
  { id: "social_27", url: "https://www.skype.com", name: "Skype", category: "social" },
  { id: "social_28", url: "https://www.meetup.com", name: "Meetup", category: "social" },
  { id: "social_29", url: "https://www.nextdoor.com", name: "Nextdoor", category: "social" },
  { id: "social_30", url: "https://www.quora.com", name: "Quora", category: "social" },
  { id: "social_31", url: "https://www.medium.com", name: "Medium", category: "social" },
  { id: "social_32", url: "https://www.slack.com", name: "Slack", category: "social" },
  { id: "social_33", url: "https://www.teams.microsoft.com", name: "Microsoft Teams", category: "social" },
  { id: "social_34", url: "https://www.zoom.us", name: "Zoom", category: "social" },
  { id: "social_35", url: "https://www.discord.gg", name: "Discord", category: "social" },
  { id: "social_36", url: "https://www.twitch.tv", name: "Twitch", category: "social" },
  { id: "social_37", url: "https://www.patreon.com", name: "Patreon", category: "social" },
  { id: "social_38", url: "https://www.substack.com", name: "Substack", category: "social" },
  { id: "social_39", url: "https://www.tinder.com", name: "Tinder", category: "social" },
  { id: "social_40", url: "https://www.bumble.com", name: "Bumble", category: "social" },
  { id: "social_41", url: "https://www.hinge.co", name: "Hinge", category: "social" },
  { id: "social_42", url: "https://www.grindr.com", name: "Grindr", category: "social" },
  { id: "social_43", url: "https://www.badoo.com", name: "Badoo", category: "social" },
  { id: "social_44", url: "https://www.okcupid.com", name: "OkCupid", category: "social" },
  { id: "social_45", url: "https://www.match.com", name: "Match", category: "social" },
  { id: "social_46", url: "https://www.pof.com", name: "Plenty of Fish", category: "social" },
  { id: "social_47", url: "https://www.zoosk.com", name: "Zoosk", category: "social" },
  { id: "social_48", url: "https://www.eharmony.com", name: "eHarmony", category: "social" },
  { id: "social_49", url: "https://www.christianmingle.com", name: "Christian Mingle", category: "social" },
  { id: "social_50", url: "https://www.jdate.com", name: "JDate", category: "social" },
  { id: "social_51", url: "https://www.farmersonly.com", name: "Farmers Only", category: "social" },
  { id: "social_52", url: "https://www.coffeemeetsbagel.com", name: "Coffee Meets Bagel", category: "social" },
  { id: "social_53", url: "https://www.happn.com", name: "Happn", category: "social" },
  { id: "social_54", url: "https://www.tantan.com", name: "Tantan", category: "social" },
  { id: "social_55", url: "https://www.momo.com", name: "Momo", category: "social" },
  { id: "social_56", url: "https://www.soul.cn", name: "Soul", category: "social" },
  { id: "social_57", url: "https://www.blued.com", name: "Blued", category: "social" },
  { id: "social_58", url: "https://www.taimi.com", name: "Taimi", category: "social" },
  { id: "social_59", url: "https://www.her.app", name: "HER", category: "social" },
  { id: "social_60", url: "https://www.scruff.com", name: "Scruff", category: "social" },
  { id: "social_61", url: "https://www.jackd.com", name: "Jack'd", category: "social" },
  { id: "social_62", url: "https://www.hornet.com", name: "Hornet", category: "social" },
  { id: "social_63", url: "https://www.growlr.com", name: "Growlr", category: "social" },
  { id: "social_64", url: "https://www.feeld.co", name: "Feeld", category: "social" },
  { id: "social_65", url: "https://www.fetlife.com", name: "FetLife", category: "social" },
  { id: "social_66", url: "https://www.adultfriendfinder.com", name: "AdultFriendFinder", category: "social" },
  { id: "social_67", url: "https://www.ashleymadison.com", name: "Ashley Madison", category: "social" },
  { id: "social_68", url: "https://www.seekingarrangement.com", name: "Seeking Arrangement", category: "social" },
  { id: "social_69", url: "https://www.sugardaddymeet.com", name: "Sugar Daddy Meet", category: "social" },
  { id: "social_70", url: "https://www.secretbenefits.com", name: "Secret Benefits", category: "social" },
  { id: "social_71", url: "https://www.whatsyourprice.com", name: "What's Your Price", category: "social" },
  { id: "social_72", url: "https://www.misstravel.com", name: "Miss Travel", category: "social" },
  { id: "social_73", url: "https://www.established.com", name: "Established Men", category: "social" },
  { id: "social_74", url: "https://www.cougarlife.com", name: "Cougar Life", category: "social" },
  { id: "social_75", url: "https://www.arrangement.com", name: "Arrangement Finders", category: "social" },
  { id: "social_76", url: "https://www.onlyfans.com", name: "OnlyFans", category: "social" },
  { id: "social_77", url: "https://www.fansly.com", name: "Fansly", category: "social" },
  { id: "social_78", url: "https://www.justforfans.com", name: "JustForFans", category: "social" },
  { id: "social_79", url: "https://www.loyalfans.com", name: "LoyalFans", category: "social" },
  { id: "social_80", url: "https://www.fancentro.com", name: "FanCentro", category: "social" },
  { id: "social_81", url: "https://www.manyvids.com", name: "ManyVids", category: "social" },
  { id: "social_82", url: "https://www.clips4sale.com", name: "Clips4Sale", category: "social" },
  { id: "social_83", url: "https://www.iwantclips.com", name: "iWantClips", category: "social" },
  { id: "social_84", url: "https://www.avnstars.com", name: "AVN Stars", category: "social" },
  { id: "social_85", url: "https://www.stars.avn.com", name: "AVN Stars", category: "social" },
  { id: "social_86", url: "https://www.pocketstars.com", name: "PocketStars", category: "social" },
  { id: "social_87", url: "https://www.frisk.chat", name: "Frisk", category: "social" },
  { id: "social_88", url: "https://www.admire.me", name: "Admire.Me", category: "social" },
  { id: "social_89", url: "https://www.ismygirl.com", name: "IsMyGirl", category: "social" },
  { id: "social_90", url: "https://www.ismyguy.com", name: "IsMyGuy", category: "social" },
  { id: "social_91", url: "https://www.modelcentro.com", name: "ModelCentro", category: "social" },
  { id: "social_92", url: "https://www.modelhub.com", name: "ModelHub", category: "social" },
  { id: "social_93", url: "https://www.pornhub.com/model", name: "Pornhub Model Program", category: "social" },
  { id: "social_94", url: "https://www.xvideos.com/model-program", name: "XVideos Model Program", category: "social" },
  { id: "social_95", url: "https://www.xhamsterlive.com", name: "xHamster Live", category: "social" },
  { id: "social_96", url: "https://www.livejasmin.com", name: "LiveJasmin", category: "social" },
  { id: "social_97", url: "https://www.chaturbate.com", name: "Chaturbate", category: "social" },
  { id: "social_98", url: "https://www.myfreecams.com", name: "MyFreeCams", category: "social" },
  { id: "social_99", url: "https://www.bongacams.com", name: "BongaCams", category: "social" },
  { id: "social_100", url: "https://www.cam4.com", name: "Cam4", category: "social" },
  { id: "social_101", url: "https://www.camsoda.com", name: "CamSoda", category: "social" },
  { id: "social_102", url: "https://www.streamate.com", name: "Streamate", category: "social" },
  { id: "social_103", url: "https://www.flirt4free.com", name: "Flirt4Free", category: "social" },
  { id: "social_104", url: "https://www.imlive.com", name: "ImLive", category: "social" },
  { id: "social_105", url: "https://www.stripchat.com", name: "Stripchat", category: "social" },
  { id: "social_106", url: "https://www.xcams.com", name: "XCams", category: "social" },
  { id: "social_107", url: "https://www.amateur.tv", name: "Amateur.tv", category: "social" },
  { id: "social_108", url: "https://www.jerkmate.com", name: "Jerkmate", category: "social" },
  { id: "social_109", url: "https://www.sakuralive.com", name: "Sakura Live", category: "social" },
  { id: "social_110", url: "https://www.asianbabecams.com", name: "Asian Babe Cams", category: "social" },
  { id: "social_111", url: "https://www.camversity.com", name: "Camversity", category: "social" },
  { id: "social_112", url: "https://www.camcontacts.com", name: "CamContacts", category: "social" },
  { id: "social_113", url: "https://www.sexier.com", name: "Sexier", category: "social" },
  { id: "social_114", url: "https://www.xlovecam.com", name: "XLoveCam", category: "social" },
  { id: "social_115", url: "https://www.liveprivates.com", name: "LivePrivates", category: "social" },
  { id: "social_116", url: "https://www.camdolls.com", name: "CamDolls", category: "social" },
  { id: "social_117", url: "https://www.camplace.com", name: "CamPlace", category: "social" },
  { id: "social_118", url: "https://www.slutroulette.com", name: "SlutRoulette", category: "social" },
  { id: "social_119", url: "https://www.flingster.com", name: "Flingster", category: "social" },
  { id: "social_120", url: "https://www.chatrandom.com", name: "ChatRandom", category: "social" },
  { id: "social_121", url: "https://www.chatroulette.com", name: "ChatRoulette", category: "social" },
  { id: "social_122", url: "https://www.omegle.com", name: "Omegle", category: "social" },
  { id: "social_123", url: "https://www.chatspin.com", name: "ChatSpin", category: "social" },
  { id: "social_124", url: "https://www.shagle.com", name: "Shagle", category: "social" },
  { id: "social_125", url: "https://www.dirtyroulette.com", name: "Dirty Roulette", category: "social" },
  { id: "social_126", url: "https://www.camfrog.com", name: "Camfrog", category: "social" },
  { id: "social_127", url: "https://www.paltalk.com", name: "Paltalk", category: "social" },
  { id: "social_128", url: "https://www.tinychat.com", name: "Tinychat", category: "social" },
  { id: "social_129", url: "https://www.chatib.com", name: "Chatib", category: "social" },
  { id: "social_130", url: "https://www.e-chat.co", name: "E-chat", category: "social" },
  { id: "social_131", url: "https://www.chat-avenue.com", name: "Chat Avenue", category: "social" },
  { id: "social_132", url: "https://www.321chat.com", name: "321Chat", category: "social" },
  { id: "social_133", url: "https://www.chatblink.com", name: "ChatBlink", category: "social" },
  { id: "social_134", url: "https://www.chatzy.com", name: "Chatzy", category: "social" },
  { id: "social_135", url: "https://www.wireclub.com", name: "Wireclub", category: "social" },
  { id: "social_136", url: "https://www.mocospace.com", name: "MocoSpace", category: "social" },
  { id: "social_137", url: "https://www.meetme.com", name: "MeetMe", category: "social" },
  { id: "social_138", url: "https://www.skout.com", name: "Skout", category: "social" },
  { id: "social_139", url: "https://www.tagged.com", name: "Tagged", category: "social" },
  { id: "social_140", url: "https://www.hi5.com", name: "Hi5", category: "social" },
  { id: "social_141", url: "https://www.blackpeoplemeet.com", name: "BlackPeopleMeet", category: "social" },
  { id: "social_142", url: "https://www.latinamericancupid.com", name: "Latin American Cupid", category: "social" },
  { id: "social_143", url: "https://www.asiandating.com", name: "Asian Dating", category: "social" },
  { id: "social_144", url: "https://www.russiancupid.com", name: "Russian Cupid", category: "social" },
  { id: "social_145", url: "https://www.ukrainedate.com", name: "Ukraine Date", category: "social" },
  { id: "social_146", url: "https://www.brazilcupid.com", name: "Brazil Cupid", category: "social" },
  { id: "social_147", url: "https://www.mexicancupid.com", name: "Mexican Cupid", category: "social" },
  { id: "social_148", url: "https://www.filipinocupid.com", name: "Filipino Cupid", category: "social" },
  { id: "social_149", url: "https://www.thailandcupid.com", name: "Thailand Cupid", category: "social" },
  { id: "social_150", url: "https://www.vietnamcupid.com", name: "Vietnam Cupid", category: "social" },
  { id: "social_151", url: "https://www.chinalovecupid.com", name: "China Love Cupid", category: "social" },
  { id: "social_152", url: "https://www.japancupid.com", name: "Japan Cupid", category: "social" },
  { id: "social_153", url: "https://www.koreancupid.com", name: "Korean Cupid", category: "social" },
  { id: "social_154", url: "https://www.hongkongcupid.com", name: "Hong Kong Cupid", category: "social" },
  { id: "social_155", url: "https://www.singaporelovelinks.com", name: "Singapore Love Links", category: "social" },
  { id: "social_156", url: "https://www.malaysiancupid.com", name: "Malaysian Cupid", category: "social" },
  { id: "social_157", url: "https://www.indonesiancupid.com", name: "Indonesian Cupid", category: "social" },
  { id: "social_158", url: "https://www.taiwancupid.com", name: "Taiwan Cupid", category: "social" },
  { id: "social_159", url: "https://www.indiancupid.com", name: "Indian Cupid", category: "social" },
  { id: "social_160", url: "https://www.pakistanicupid.com", name: "Pakistani Cupid", category: "social" },
  {
    id: "social_161",
    url: "https://www.iraniansinglesconnection.com",
    name: "Iranian Singles Connection",
    category: "social",
  },
  { id: "social_162", url: "https://www.arablounge.com", name: "Arab Lounge", category: "social" },
  { id: "social_163", url: "https://www.lovehabibi.com", name: "LoveHabibi", category: "social" },
  { id: "social_164", url: "https://www.muslima.com", name: "Muslima", category: "social" },
  { id: "social_165", url: "https://www.arabiandate.com", name: "Arabian Date", category: "social" },
  { id: "social_166", url: "https://www.afrointroductions.com", name: "Afro Introductions", category: "social" },
  { id: "social_167", url: "https://www.afroromance.com", name: "AfroRomance", category: "social" },
  { id: "social_168", url: "https://www.kenyansingles.com", name: "Kenyan Singles", category: "social" },
  { id: "social_169", url: "https://www.southafricancupid.com", name: "South African Cupid", category: "social" },
  { id: "social_170", url: "https://www.nigeriansingles.com", name: "Nigerian Singles", category: "social" },
  { id: "social_171", url: "https://www.ghanasingles.com", name: "Ghana Singles", category: "social" },
  { id: "social_172", url: "https://www.ethiopianpersonals.com", name: "Ethiopian Personals", category: "social" },
  { id: "social_173", url: "https://www.caribbeancupid.com", name: "Caribbean Cupid", category: "social" },
  { id: "social_174", url: "https://www.dominicansingles.com", name: "Dominican Singles", category: "social" },
  { id: "social_175", url: "https://www.colombiancupid.com", name: "Colombian Cupid", category: "social" },
  { id: "social_176", url: "https://www.mexicancupid.com", name: "Mexican Cupid", category: "social" },
  { id: "social_177", url: "https://www.brazilcupid.com", name: "Brazil Cupid", category: "social" },
  { id: "social_178", url: "https://www.peruviansingles.com", name: "Peruvian Singles", category: "social" },
  { id: "social_179", url: "https://www.venezuelansingles.com", name: "Venezuelan Singles", category: "social" },
  { id: "social_180", url: "https://www.argentinesingles.com", name: "Argentine Singles", category: "social" },
  { id: "social_181", url: "https://www.chileansingles.com", name: "Chilean Singles", category: "social" },
  { id: "social_182", url: "https://www.ecuadoriansingles.com", name: "Ecuadorian Singles", category: "social" },
  { id: "social_183", url: "https://www.australiancupid.com", name: "Australian Cupid", category: "social" },
  { id: "social_184", url: "https://www.newzealandcupid.com", name: "New Zealand Cupid", category: "social" },
  { id: "social_185", url: "https://www.britishcupid.com", name: "British Cupid", category: "social" },
  { id: "social_186", url: "https://www.irishdating.com", name: "Irish Dating", category: "social" },
  { id: "social_187", url: "https://www.scottishsingles.com", name: "Scottish Singles", category: "social" },
  { id: "social_188", url: "https://www.frenchcupid.com", name: "French Cupid", category: "social" },
  { id: "social_189", url: "https://www.germancupid.com", name: "German Cupid", category: "social" },
  { id: "social_190", url: "https://www.italiancupid.com", name: "Italian Cupid", category: "social" },
  { id: "social_191", url: "https://www.spanishcupid.com", name: "Spanish Cupid", category: "social" },
  { id: "social_192", url: "https://www.portuguesecupid.com", name: "Portuguese Cupid", category: "social" },
  { id: "social_193", url: "https://www.greeksingles.com", name: "Greek Singles", category: "social" },
  { id: "social_194", url: "https://www.turkishpersonals.com", name: "Turkish Personals", category: "social" },
  { id: "social_195", url: "https://www.polishhearts.com", name: "Polish Hearts", category: "social" },
  { id: "social_196", url: "https://www.czechcupid.com", name: "Czech Cupid", category: "social" },
  { id: "social_197", url: "https://www.slovakiancupid.com", name: "Slovakian Cupid", category: "social" },
  { id: "social_198", url: "https://www.hungariancupid.com", name: "Hungarian Cupid", category: "social" },
  { id: "social_199", url: "https://www.romaniancupid.com", name: "Romanian Cupid", category: "social" },
  { id: "social_200", url: "https://www.bulgariancupid.com", name: "Bulgarian Cupid", category: "social" },
  { id: "social_201", url: "https://www.serbiancupid.com", name: "Serbian Cupid", category: "social" },
  { id: "social_202", url: "https://www.croatiancupid.com", name: "Croatian Cupid", category: "social" },
  { id: "social_203", url: "https://www.albaniancupid.com", name: "Albanian Cupid", category: "social" },
  { id: "social_204", url: "https://www.macedoniancupid.com", name: "Macedonian Cupid", category: "social" },
  { id: "social_205", url: "https://www.bosniancupid.com", name: "Bosnian Cupid", category: "social" },
  { id: "social_206", url: "https://www.montenegrocupid.com", name: "Montenegro Cupid", category: "social" },
  { id: "social_207", url: "https://www.sloveniancupid.com", name: "Slovenian Cupid", category: "social" },
  { id: "social_208", url: "https://www.estoniancupid.com", name: "Estonian Cupid", category: "social" },
  { id: "social_209", url: "https://www.latviancupid.com", name: "Latvian Cupid", category: "social" },
  { id: "social_210", url: "https://www.lithuaniancupid.com", name: "Lithuanian Cupid", category: "social" },
  { id: "social_211", url: "https://www.belarusiancupid.com", name: "Belarusian Cupid", category: "social" },
  { id: "social_212", url: "https://www.moldovancupid.com", name: "Moldovan Cupid", category: "social" },
  { id: "social_213", url: "https://www.ukrainiancupid.com", name: "Ukrainian Cupid", category: "social" },
  { id: "social_214", url: "https://www.russiancupid.com", name: "Russian Cupid", category: "social" },
  { id: "social_215", url: "https://www.kazakh-dating.com", name: "Kazakh Dating", category: "social" },
  { id: "social_216", url: "https://www.uzbekcupid.com", name: "Uzbek Cupid", category: "social" },
  { id: "social_217", url: "https://www.kyrgyzsingles.com", name: "Kyrgyz Singles", category: "social" },
  { id: "social_218", url: "https://www.tajiksingles.com", name: "Tajik Singles", category: "social" },
  { id: "social_219", url: "https://www.turkmensingles.com", name: "Turkmen Singles", category: "social" },
  { id: "social_220", url: "https://www.azerbaijanisingles.com", name: "Azerbaijani Singles", category: "social" },
  { id: "social_221", url: "https://www.armeniansingles.com", name: "Armenian Singles", category: "social" },
  { id: "social_222", url: "https://www.georgiansingles.com", name: "Georgian Singles", category: "social" },
  { id: "social_223", url: "https://www.mongoliansingles.com", name: "Mongolian Singles", category: "social" },
  { id: "social_224", url: "https://www.nepalisingles.com", name: "Nepali Singles", category: "social" },
  { id: "social_225", url: "https://www.bhutanesesingles.com", name: "Bhutanese Singles", category: "social" },
  { id: "social_226", url: "https://www.bangladeshisingles.com", name: "Bangladeshi Singles", category: "social" },
  { id: "social_227", url: "https://www.srilankansingles.com", name: "Sri Lankan Singles", category: "social" },
  { id: "social_228", url: "https://www.maldiviansingles.com", name: "Maldivian Singles", category: "social" },
  { id: "social_229", url: "https://www.afghansingles.com", name: "Afghan Singles", category: "social" },
  { id: "social_230", url: "https://www.israelisingles.com", name: "Israeli Singles", category: "social" },
  { id: "social_231", url: "https://www.lebanesesingles.com", name: "Lebanese Singles", category: "social" },
  { id: "social_232", url: "https://www.jordaniansingles.com", name: "Jordanian Singles", category: "social" },
  { id: "social_233", url: "https://www.syriansingles.com", name: "Syrian Singles", category: "social" },
  { id: "social_234", url: "https://www.iraqisingles.com", name: "Iraqi Singles", category: "social" },
  { id: "social_235", url: "https://www.kuwaitisingles.com", name: "Kuwaiti Singles", category: "social" },
  { id: "social_236", url: "https://www.bahrainisingles.com", name: "Bahraini Singles", category: "social" },
  { id: "social_237", url: "https://www.qatarisingles.com", name: "Qatari Singles", category: "social" },
  { id: "social_238", url: "https://www.uaesingles.com", name: "UAE Singles", category: "social" },
  { id: "social_239", url: "https://www.omanisingles.com", name: "Omani Singles", category: "social" },
  { id: "social_240", url: "https://www.yemenisingles.com", name: "Yemeni Singles", category: "social" },
  { id: "social_241", url: "https://www.saudisingles.com", name: "Saudi Singles", category: "social" },
  { id: "social_242", url: "https://www.egyptiansingles.com", name: "Egyptian Singles", category: "social" },
  { id: "social_243", url: "https://www.libyansingles.com", name: "Libyan Singles", category: "social" },
  { id: "social_244", url: "https://www.tunisiansingles.com", name: "Tunisian Singles", category: "social" },
  { id: "social_245", url: "https://www.algeriansingles.com", name: "Algerian Singles", category: "social" },
  { id: "social_246", url: "https://www.moroccansingles.com", name: "Moroccan Singles", category: "social" },
  { id: "social_247", url: "https://www.mauritaniansingles.com", name: "Mauritanian Singles", category: "social" },
  { id: "social_248", url: "https://www.malisingles.com", name: "Mali Singles", category: "social" },
  { id: "social_249", url: "https://www.nigersingles.com", name: "Niger Singles", category: "social" },
  { id: "social_250", url: "https://www.chadsingles.com", name: "Chad Singles", category: "social" },
  { id: "social_251", url: "https://www.sudaneseingles.com", name: "Sudanese Singles", category: "social" },
  { id: "social_252", url: "https://www.southsudanesesingles.com", name: "South Sudanese Singles", category: "social" },
  { id: "social_253", url: "https://www.eritreansingles.com", name: "Eritrean Singles", category: "social" },
  { id: "social_254", url: "https://www.djiboutiansingles.com", name: "Djiboutian Singles", category: "social" },
  { id: "social_255", url: "https://www.somaliansingles.com", name: "Somalian Singles", category: "social" },
  { id: "social_256", url: "https://www.ethiopiansingles.com", name: "Ethiopian Singles", category: "social" },
  { id: "social_257", url: "https://www.ugandansingles.com", name: "Ugandan Singles", category: "social" },
  { id: "social_258", url: "https://www.rwandansingles.com", name: "Rwandan Singles", category: "social" },
  { id: "social_259", url: "https://www.burundisingles.com", name: "Burundi Singles", category: "social" },
  { id: "social_260", url: "https://www.tanzaniansingles.com", name: "Tanzanian Singles", category: "social" },
  { id: "social_261", url: "https://www.kenyansingles.com", name: "Kenyan Singles", category: "social" },
  { id: "social_262", url: "https://www.congosingles.com", name: "Congo Singles", category: "social" },
  { id: "social_263", url: "https://www.angolansingles.com", name: "Angolan Singles", category: "social" },
  { id: "social_264", url: "https://www.zambiansingles.com", name: "Zambian Singles", category: "social" },
  { id: "social_265", url: "https://www.zimbabweansingles.com", name: "Zimbabwean Singles", category: "social" },
  { id: "social_266", url: "https://www.mozambicansingles.com", name: "Mozambican Singles", category: "social" },
  { id: "social_267", url: "https://www.namibiansingles.com", name: "Namibian Singles", category: "social" },
  { id: "social_268", url: "https://www.botswanasingles.com", name: "Botswana Singles", category: "social" },
  { id: "social_269", url: "https://www.southafricansingles.com", name: "South African Singles", category: "social" },
  { id: "social_270", url: "https://www.lesothosingles.com", name: "Lesotho Singles", category: "social" },
  { id: "social_271", url: "https://www.eswatinisingles.com", name: "Eswatini Singles", category: "social" },
  { id: "social_272", url: "https://www.madagascarsingles.com", name: "Madagascar Singles", category: "social" },
  { id: "social_273", url: "https://www.comoriansingles.com", name: "Comorian Singles", category: "social" },
  { id: "social_274", url: "https://www.mauritiansingles.com", name: "Mauritian Singles", category: "social" },
  { id: "social_275", url: "https://www.seychellessingles.com", name: "Seychelles Singles", category: "social" },
  { id: "social_276", url: "https://www.capeverdesingles.com", name: "Cape Verde Singles", category: "social" },
  { id: "social_277", url: "https://www.saotomesingles.com", name: "São Tomé Singles", category: "social" },
  { id: "social_278", url: "https://www.guineabissausingles.com", name: "Guinea-Bissau Singles", category: "social" },
  { id: "social_279", url: "https://www.guineansingles.com", name: "Guinean Singles", category: "social" },
  { id: "social_280", url: "https://www.sierraleoneansingles.com", name: "Sierra Leonean Singles", category: "social" },
  { id: "social_281", url: "https://www.liberiansingles.com", name: "Liberian Singles", category: "social" },
  { id: "social_282", url: "https://www.ivoriansingles.com", name: "Ivorian Singles", category: "social" },
  { id: "social_283", url: "https://www.burkinabesingles.com", name: "Burkinabe Singles", category: "social" },
  { id: "social_284", url: "https://www.ghanaiansingles.com", name: "Ghanaian Singles", category: "social" },
  { id: "social_285", url: "https://www.togoleseingles.com", name: "Togolese Singles", category: "social" },
  { id: "social_286", url: "https://www.beninsingles.com", name: "Benin Singles", category: "social" },
  { id: "social_287", url: "https://www.nigeriansingles.com", name: "Nigerian Singles", category: "social" },
  { id: "social_288", url: "https://www.camerooniansingles.com", name: "Cameroonian Singles", category: "social" },
  {
    id: "social_289",
    url: "https://www.centralafricansingles.com",
    name: "Central African Singles",
    category: "social",
  },
  {
    id: "social_290",
    url: "https://www.equatorialguineansingles.com",
    name: "Equatorial Guinean Singles",
    category: "social",
  },
  { id: "social_291", url: "https://www.gaboneseingles.com", name: "Gabonese Singles", category: "social" },
  { id: "social_292", url: "https://www.congoleseingles.com", name: "Congolese Singles", category: "social" },
  { id: "social_293", url: "https://www.senegalesesingles.com", name: "Senegalese Singles", category: "social" },
  { id: "social_294", url: "https://www.gambiansingles.com", name: "Gambian Singles", category: "social" },
  { id: "social_295", url: "https://www.fijiansingles.com", name: "Fijian Singles", category: "social" },
  { id: "social_296", url: "https://www.samoasingles.com", name: "Samoa Singles", category: "social" },
  { id: "social_297", url: "https://www.tongasingles.com", name: "Tonga Singles", category: "social" },
  { id: "social_298", url: "https://www.vanuatusingles.com", name: "Vanuatu Singles", category: "social" },
  {
    id: "social_299",
    url: "https://www.solomonislandssingles.com",
    name: "Solomon Islands Singles",
    category: "social",
  },
  {
    id: "social_300",
    url: "https://www.papuanewguineansingles.com",
    name: "Papua New Guinean Singles",
    category: "social",
  },
  { id: "social_301", url: "https://www.micronesiansingles.com", name: "Micronesian Singles", category: "social" },
  { id: "social_302", url: "https://www.marshallesesingles.com", name: "Marshallese Singles", category: "social" },
  { id: "social_303", url: "https://www.palauansingles.com", name: "Palauan Singles", category: "social" },
  { id: "social_304", url: "https://www.nauruansingles.com", name: "Nauruan Singles", category: "social" },
  { id: "social_305", url: "https://www.kiribatisingles.com", name: "Kiribati Singles", category: "social" },
  { id: "social_306", url: "https://www.tuvaluansingles.com", name: "Tuvaluan Singles", category: "social" },
  { id: "social_307", url: "https://www.cookislandssingles.com", name: "Cook Islands Singles", category: "social" },
  { id: "social_308", url: "https://www.niueansingles.com", name: "Niuean Singles", category: "social" },
  { id: "social_309", url: "https://www.tokelauansingles.com", name: "Tokelauan Singles", category: "social" },
  {
    id: "social_310",
    url: "https://www.pitcairnislandssingles.com",
    name: "Pitcairn Islands Singles",
    category: "social",
  },
  {
    id: "social_311",
    url: "https://www.frenchpolynesiansingles.com",
    name: "French Polynesian Singles",
    category: "social",
  },
  { id: "social_312", url: "https://www.newcaledoniansingles.com", name: "New Caledonian Singles", category: "social" },
  {
    id: "social_313",
    url: "https://www.wallisandfutunasingles.com",
    name: "Wallis and Futuna Singles",
    category: "social",
  },
  {
    id: "social_314",
    url: "https://www.americansamoansingles.com",
    name: "American Samoan Singles",
    category: "social",
  },
  { id: "social_315", url: "https://www.guamsingles.com", name: "Guam Singles", category: "social" },
  {
    id: "social_316",
    url: "https://www.northernmarianasislandssingles.com",
    name: "Northern Marianas Islands Singles",
    category: "social",
  },
  {
    id: "social_317",
    url: "https://www.usvirginislandssingles.com",
    name: "US Virgin Islands Singles",
    category: "social",
  },
  { id: "social_318", url: "https://www.puertoricancupid.com", name: "Puerto Rican Cupid", category: "social" },
  { id: "social_319", url: "https://www.hawaiiansingles.com", name: "Hawaiian Singles", category: "social" },
  { id: "social_320", url: "https://www.alaskansingles.com", name: "Alaskan Singles", category: "social" },
  { id: "social_321", url: "https://www.canadiancupid.com", name: "Canadian Cupid", category: "social" },
  { id: "social_322", url: "https://www.quebecsingles.com", name: "Quebec Singles", category: "social" },
  { id: "social_323", url: "https://www.mexicancupid.com", name: "Mexican Cupid", category: "social" },
  { id: "social_324", url: "https://www.guatemalansingles.com", name: "Guatemalan Singles", category: "social" },
  { id: "social_325", url: "https://www.belizeansingles.com", name: "Belizean Singles", category: "social" },
  { id: "social_326", url: "https://www.salvadoransingles.com", name: "Salvadoran Singles", category: "social" },
  { id: "social_327", url: "https://www.honduransingles.com", name: "Honduran Singles", category: "social" },
  { id: "social_328", url: "https://www.nicaraguansingles.com", name: "Nicaraguan Singles", category: "social" },
  { id: "social_329", url: "https://www.costaricancupid.com", name: "Costa Rican Cupid", category: "social" },
  { id: "social_330", url: "https://www.panamacupid.com", name: "Panama Cupid", category: "social" },
  { id: "social_331", url: "https://www.bahamassingles.com", name: "Bahamas Singles", category: "social" },
  { id: "social_332", url: "https://www.cubansingles.com", name: "Cuban Singles", category: "social" },
  { id: "social_333", url: "https://www.jamaicansingles.com", name: "Jamaican Singles", category: "social" },
  { id: "social_334", url: "https://www.haitiansingles.com", name: "Haitian Singles", category: "social" },
  { id: "social_335", url: "https://www.dominicansingles.com", name: "Dominican Singles", category: "social" },
  {
    id: "social_336",
    url: "https://www.trinidadandtobagosingles.com",
    name: "Trinidad and Tobago Singles",
    category: "social",
  },
  { id: "social_337", url: "https://www.barbadiansingles.com", name: "Barbadian Singles", category: "social" },
  { id: "social_338", url: "https://www.saintluciansingles.com", name: "Saint Lucian Singles", category: "social" },
  { id: "social_339", url: "https://www.grenadiansingles.com", name: "Grenadian Singles", category: "social" },
  { id: "social_340", url: "https://www.vincentiansingles.com", name: "Vincentian Singles", category: "social" },
  { id: "social_341", url: "https://www.antiguansingles.com", name: "Antiguan Singles", category: "social" },
  { id: "social_342", url: "https://www.kittitiansingles.com", name: "Kittitian Singles", category: "social" },
  { id: "social_343", url: "https://www.dominicasingles.com", name: "Dominica Singles", category: "social" },
  { id: "social_344", url: "https://www.colombiancupid.com", name: "Colombian Cupid", category: "social" },
  { id: "social_345", url: "https://www.venezuelansingles.com", name: "Venezuelan Singles", category: "social" },
  { id: "social_346", url: "https://www.guyaneseingles.com", name: "Guyanese Singles", category: "social" },
  { id: "social_347", url: "https://www.surinameseingles.com", name: "Surinamese Singles", category: "social" },
  { id: "social_348", url: "https://www.frenchguianasingles.com", name: "French Guiana Singles", category: "social" },
  { id: "social_349", url: "https://www.ecuadoriancupid.com", name: "Ecuadorian Cupid", category: "social" },
  { id: "social_350", url: "https://www.peruviancupid.com", name: "Peruvian Cupid", category: "social" },
  { id: "social_351", url: "https://www.boliviansingles.com", name: "Bolivian Singles", category: "social" },
  { id: "social_352", url: "https://www.paraguayansingles.com", name: "Paraguayan Singles", category: "social" },
  { id: "social_353", url: "https://www.uruguayansingles.com", name: "Uruguayan Singles", category: "social" },
  { id: "social_354", url: "https://www.argentinecupid.com", name: "Argentine Cupid", category: "social" },
  { id: "social_355", url: "https://www.chileansingles.com", name: "Chilean Singles", category: "social" },
  {
    id: "social_356",
    url: "https://www.falklandislandssingles.com",
    name: "Falkland Islands Singles",
    category: "social",
  },
  { id: "social_357", url: "https://www.icelandicsingles.com", name: "Icelandic Singles", category: "social" },
  { id: "social_358", url: "https://www.norwegiansingles.com", name: "Norwegian Singles", category: "social" },
  { id: "social_359", url: "https://www.swedishsingles.com", name: "Swedish Singles", category: "social" },
  { id: "social_360", url: "https://www.finnishsingles.com", name: "Finnish Singles", category: "social" },
  { id: "social_361", url: "https://www.danishsingles.com", name: "Danish Singles", category: "social" },
  { id: "social_362", url: "https://www.faeroeislandssingles.com", name: "Faroe Islands Singles", category: "social" },
  { id: "social_363", url: "https://www.greenlandicsingles.com", name: "Greenlandic Singles", category: "social" },
  { id: "social_364", url: "https://www.dutchsingles.com", name: "Dutch Singles", category: "social" },
  { id: "social_365", url: "https://www.belgiansingles.com", name: "Belgian Singles", category: "social" },
  { id: "social_366", url: "https://www.luxembourgishsingles.com", name: "Luxembourgish Singles", category: "social" },
  { id: "social_367", url: "https://www.swisscupid.com", name: "Swiss Cupid", category: "social" },
  { id: "social_368", url: "https://www.liechtensteinsingles.com", name: "Liechtenstein Singles", category: "social" },
  { id: "social_369", url: "https://www.austriancupid.com", name: "Austrian Cupid", category: "social" },
  { id: "social_370", url: "https://www.germancupid.com", name: "German Cupid", category: "social" },
  { id: "social_371", url: "https://www.frenchcupid.com", name: "French Cupid", category: "social" },
  { id: "social_372", url: "https://www.monacoansingles.com", name: "Monacan Singles", category: "social" },
  { id: "social_373", url: "https://www.andorransingles.com", name: "Andorran Singles", category: "social" },
  { id: "social_374", url: "https://www.spanishcupid.com", name: "Spanish Cupid", category: "social" },
  { id: "social_375", url: "https://www.gibraltarsingles.com", name: "Gibraltar Singles", category: "social" },
  { id: "social_376", url: "https://www.portuguesecupid.com", name: "Portuguese Cupid", category: "social" },
  { id: "social_377", url: "https://www.italiansingles.com", name: "Italian Singles", category: "social" },
  { id: "social_378", url: "https://www.sanmarineseingles.com", name: "Sanmarinese Singles", category: "social" },
  { id: "social_379", url: "https://www.vaticansingles.com", name: "Vatican Singles", category: "social" },
  { id: "social_380", url: "https://www.maltesesingles.com", name: "Maltese Singles", category: "social" },
  { id: "social_381", url: "https://www.greeksingles.com", name: "Greek Singles", category: "social" },
  { id: "social_382", url: "https://www.cypriotsingles.com", name: "Cypriot Singles", category: "social" },
  { id: "social_383", url: "https://www.turkishsingles.com", name: "Turkish Singles", category: "social" },
  { id: "social_384", url: "https://www.britishcupid.com", name: "British Cupid", category: "social" },
  { id: "social_385", url: "https://www.irishsingles.com", name: "Irish Singles", category: "social" },
  { id: "social_386", url: "https://www.polishsingles.com", name: "Polish Singles", category: "social" },
  { id: "social_387", url: "https://www.czechsingles.com", name: "Czech Singles", category: "social" },
  { id: "social_388", url: "https://www.slovaksingles.com", name: "Slovak Singles", category: "social" },
  { id: "social_389", url: "https://www.hungariansingles.com", name: "Hungarian Singles", category: "social" },
  { id: "social_390", url: "https://www.romaniansingles.com", name: "Romanian Singles", category: "social" },
  { id: "social_391", url: "https://www.bulgariansingles.com", name: "Bulgarian Singles", category: "social" },
  { id: "social_392", url: "https://www.albaniansingles.com", name: "Albanian Singles", category: "social" },
  {
    id: "social_393",
    url: "https://www.northmacedoniansingles.com",
    name: "North Macedonian Singles",
    category: "social",
  },
  { id: "social_394", url: "https://www.kosovosingles.com", name: "Kosovo Singles", category: "social" },
  { id: "social_395", url: "https://www.montenegrinsingles.com", name: "Montenegrin Singles", category: "social" },
  { id: "social_396", url: "https://www.serbiansingles.com", name: "Serbian Singles", category: "social" },
  { id: "social_397", url: "https://www.bosniansingles.com", name: "Bosnian Singles", category: "social" },
  { id: "social_398", url: "https://www.croatiansingles.com", name: "Croatian Singles", category: "social" },
  { id: "social_399", url: "https://www.sloveniansingles.com", name: "Slovenian Singles", category: "social" },
  { id: "social_400", url: "https://www.moldovansingles.com", name: "Moldovan Singles", category: "social" },
  { id: "social_401", url: "https://www.ukrainiansingles.com", name: "Ukrainian Singles", category: "social" },
  { id: "social_402", url: "https://www.belarusiansingles.com", name: "Belarusian Singles", category: "social" },
  { id: "social_403", url: "https://www.russiansingles.com", name: "Russian Singles", category: "social" },
  { id: "social_404", url: "https://www.lithuaniansingles.com", name: "Lithuanian Singles", category: "social" },
  { id: "social_405", url: "https://www.latviansingles.com", name: "Latvian Singles", category: "social" },
  { id: "social_406", url: "https://www.estoniansingles.com", name: "Estonian Singles", category: "social" },
  { id: "social_407", url: "https://www.facebook.com/groups", name: "Facebook Groups", category: "social" },
  { id: "social_408", url: "https://www.facebook.com/marketplace", name: "Facebook Marketplace", category: "social" },
  { id: "social_409", url: "https://www.facebook.com/gaming", name: "Facebook Gaming", category: "social" },
  { id: "social_410", url: "https://www.facebook.com/watch", name: "Facebook Watch", category: "social" },
  { id: "social_411", url: "https://www.instagram.com/explore", name: "Instagram Explore", category: "social" },
  { id: "social_412", url: "https://www.instagram.com/reels", name: "Instagram Reels", category: "social" },
  { id: "social_413", url: "https://www.instagram.com/shop", name: "Instagram Shop", category: "social" },
  { id: "social_414", url: "https://www.twitter.com/explore", name: "Twitter Explore", category: "social" },
  { id: "social_415", url: "https://www.twitter.com/i/communities", name: "Twitter Communities", category: "social" },
  { id: "social_416", url: "https://www.twitter.com/i/bookmarks", name: "Twitter Bookmarks", category: "social" },
  { id: "social_417", url: "https://www.linkedin.com/jobs", name: "LinkedIn Jobs", category: "social" },
  { id: "social_418", url: "https://www.linkedin.com/learning", name: "LinkedIn Learning", category: "social" },
  { id: "social_419", url: "https://www.linkedin.com/salary", name: "LinkedIn Salary", category: "social" },
  { id: "social_420", url: "https://www.pinterest.com/today", name: "Pinterest Today", category: "social" },
  { id: "social_421", url: "https://www.pinterest.com/shop", name: "Pinterest Shop", category: "social" },
  { id: "social_422", url: "https://www.reddit.com/r/popular", name: "Reddit Popular", category: "social" },
  { id: "social_423", url: "https://www.reddit.com/r/all", name: "Reddit All", category: "social" },
  { id: "social_424", url: "https://www.reddit.com/r/random", name: "Reddit Random", category: "social" },
  { id: "social_425", url: "https://www.reddit.com/r/askreddit", name: "Reddit AskReddit", category: "social" },
  { id: "social_426", url: "https://www.reddit.com/r/iama", name: "Reddit IAmA", category: "social" },
  { id: "social_427", url: "https://www.reddit.com/r/news", name: "Reddit News", category: "social" },
  { id: "social_428", url: "https://www.reddit.com/r/worldnews", name: "Reddit World News", category: "social" },
  { id: "social_429", url: "https://www.reddit.com/r/politics", name: "Reddit Politics", category: "social" },
  { id: "social_430", url: "https://www.reddit.com/r/science", name: "Reddit Science", category: "social" },
  { id: "social_431", url: "https://www.reddit.com/r/technology", name: "Reddit Technology", category: "social" },
  { id: "social_432", url: "https://www.reddit.com/r/gaming", name: "Reddit Gaming", category: "social" },
  { id: "social_433", url: "https://www.reddit.com/r/movies", name: "Reddit Movies", category: "social" },
  { id: "social_434", url: "https://www.reddit.com/r/television", name: "Reddit Television", category: "social" },
  { id: "social_435", url: "https://www.reddit.com/r/music", name: "Reddit Music", category: "social" },
  { id: "social_436", url: "https://www.reddit.com/r/books", name: "Reddit Books", category: "social" },
  { id: "social_437", url: "https://www.reddit.com/r/art", name: "Reddit Art", category: "social" },
  { id: "social_438", url: "https://www.reddit.com/r/food", name: "Reddit Food", category: "social" },
  { id: "social_439", url: "https://www.reddit.com/r/fitness", name: "Reddit Fitness", category: "social" },
  { id: "social_440", url: "https://www.reddit.com/r/sports", name: "Reddit Sports", category: "social" },
  {
    id: "social_441",
    url: "https://www.reddit.com/r/personalfinance",
    name: "Reddit Personal Finance",
    category: "social",
  },
  {
    id: "social_442",
    url: "https://www.reddit.com/r/explainlikeimfive",
    name: "Reddit Explain Like I'm Five",
    category: "social",
  },
  {
    id: "social_443",
    url: "https://www.reddit.com/r/todayilearned",
    name: "Reddit Today I Learned",
    category: "social",
  },
  { id: "social_444", url: "https://www.reddit.com/r/lifeprotips", name: "Reddit Life Pro Tips", category: "social" },
  {
    id: "social_445",
    url: "https://www.reddit.com/r/showerthoughts",
    name: "Reddit Shower Thoughts",
    category: "social",
  },
  { id: "social_446", url: "https://www.reddit.com/r/jokes", name: "Reddit Jokes", category: "social" },
  { id: "social_447", url: "https://www.reddit.com/r/funny", name: "Reddit Funny", category: "social" },
  {
    id: "social_448",
    url: "https://www.reddit.com/r/mildlyinteresting",
    name: "Reddit Mildly Interesting",
    category: "social",
  },
  {
    id: "social_449",
    url: "https://www.reddit.com/r/interestingasfuck",
    name: "Reddit Interesting As Fuck",
    category: "social",
  },
  {
    id: "social_450",
    url: "https://www.reddit.com/r/dataisbeautiful",
    name: "Reddit Data Is Beautiful",
    category: "social",
  },
  { id: "social_451", url: "https://www.reddit.com/r/space", name: "Reddit Space", category: "social" },
  { id: "social_452", url: "https://www.reddit.com/r/history", name: "Reddit History", category: "social" },
  { id: "social_453", url: "https://www.reddit.com/r/philosophy", name: "Reddit Philosophy", category: "social" },
  { id: "social_454", url: "https://www.reddit.com/r/askscience", name: "Reddit Ask Science", category: "social" },
  {
    id: "social_455",
    url: "https://www.reddit.com/r/askhistorians",
    name: "Reddit Ask Historians",
    category: "social",
  },
  {
    id: "social_456",
    url: "https://www.reddit.com/r/nostupidquestions",
    name: "Reddit No Stupid Questions",
    category: "social",
  },
  {
    id: "social_457",
    url: "https://www.reddit.com/r/outoftheloop",
    name: "Reddit Out Of The Loop",
    category: "social",
  },
  { id: "social_458", url: "https://www.reddit.com/r/changemyview", name: "Reddit Change My View", category: "social" },
  {
    id: "social_459",
    url: "https://www.reddit.com/r/unpopularopinion",
    name: "Reddit Unpopular Opinion",
    category: "social",
  },
  {
    id: "social_460",
    url: "https://www.reddit.com/r/amitheasshole",
    name: "Reddit Am I The Asshole",
    category: "social",
  },
  {
    id: "social_461",
    url: "https://www.reddit.com/r/relationship_advice",
    name: "Reddit Relationship Advice",
    category: "social",
  },
  { id: "social_462", url: "https://www.reddit.com/r/legaladvice", name: "Reddit Legal Advice", category: "social" },
  {
    id: "social_463",
    url: "https://www.reddit.com/r/malefashionadvice",
    name: "Reddit Male Fashion Advice",
    category: "social",
  },
  {
    id: "social_464",
    url: "https://www.reddit.com/r/femalefashionadvice",
    name: "Reddit Female Fashion Advice",
    category: "social",
  },
  {
    id: "social_465",
    url: "https://www.reddit.com/r/skincareaddiction",
    name: "Reddit Skincare Addiction",
    category: "social",
  },
  {
    id: "social_466",
    url: "https://www.reddit.com/r/makeupaddiction",
    name: "Reddit Makeup Addiction",
    category: "social",
  },
  { id: "social_467", url: "https://www.reddit.com/r/travel", name: "Reddit Travel", category: "social" },
  { id: "social_468", url: "https://www.reddit.com/r/earthporn", name: "Reddit Earth Porn", category: "social" },
  {
    id: "social_469",
    url: "https://www.reddit.com/r/itookapicture",
    name: "Reddit I Took A Picture",
    category: "social",
  },
  {
    id: "social_470",
    url: "https://www.reddit.com/r/photoshopbattles",
    name: "Reddit Photoshop Battles",
    category: "social",
  },
  { id: "social_471", url: "https://www.reddit.com/r/aww", name: "Reddit Aww", category: "social" },
  { id: "social_472", url: "https://www.reddit.com/r/cats", name: "Reddit Cats", category: "social" },
  { id: "social_473", url: "https://www.reddit.com/r/dogs", name: "Reddit Dogs", category: "social" },
  { id: "social_474", url: "https://www.reddit.com/r/rarepuppers", name: "Reddit Rare Puppers", category: "social" },
  {
    id: "social_475",
    url: "https://www.reddit.com/r/animalsbeingjerks",
    name: "Reddit Animals Being Jerks",
    category: "social",
  },
  {
    id: "social_476",
    url: "https://www.reddit.com/r/animalsbeingbros",
    name: "Reddit Animals Being Bros",
    category: "social",
  },
  {
    id: "social_477",
    url: "https://www.reddit.com/r/natureisfuckinglit",
    name: "Reddit Nature Is Fucking Lit",
    category: "social",
  },
  { id: "social_478", url: "https://www.reddit.com/r/diy", name: "Reddit DIY", category: "social" },
  {
    id: "social_479",
    url: "https://www.reddit.com/r/homeimprovement",
    name: "Reddit Home Improvement",
    category: "social",
  },
  { id: "social_480", url: "https://www.reddit.com/r/gardening", name: "Reddit Gardening", category: "social" },
  { id: "social_481", url: "https://www.reddit.com/r/cooking", name: "Reddit Cooking", category: "social" },
  { id: "social_482", url: "https://www.reddit.com/r/baking", name: "Reddit Baking", category: "social" },
  { id: "social_483", url: "https://www.reddit.com/r/gifrecipes", name: "Reddit GIF Recipes", category: "social" },
  {
    id: "social_484",
    url: "https://www.reddit.com/r/eatcheapandhealthy",
    name: "Reddit Eat Cheap And Healthy",
    category: "social",
  },
  {
    id: "social_485",
    url: "https://www.reddit.com/r/mealprepsunday",
    name: "Reddit Meal Prep Sunday",
    category: "social",
  },
  { id: "social_486", url: "https://www.reddit.com/r/slowcooking", name: "Reddit Slow Cooking", category: "social" },
  { id: "social_487", url: "https://www.reddit.com/r/frugal", name: "Reddit Frugal", category: "social" },
  {
    id: "social_488",
    url: "https://www.reddit.com/r/buyitforlife",
    name: "Reddit Buy It For Life",
    category: "social",
  },
  { id: "social_489", url: "https://www.reddit.com/r/minimalism", name: "Reddit Minimalism", category: "social" },
  { id: "social_490", url: "https://www.reddit.com/r/zerowaste", name: "Reddit Zero Waste", category: "social" },
  { id: "social_491", url: "https://www.reddit.com/r/konmari", name: "Reddit KonMari", category: "social" },
  { id: "social_492", url: "https://www.reddit.com/r/simpleliving", name: "Reddit Simple Living", category: "social" },
  {
    id: "social_493",
    url: "https://www.reddit.com/r/financialindependence",
    name: "Reddit Financial Independence",
    category: "social",
  },
  { id: "social_494", url: "https://www.reddit.com/r/fire", name: "Reddit FIRE", category: "social" },
  { id: "social_495", url: "https://www.reddit.com/r/investing", name: "Reddit Investing", category: "social" },
  {
    id: "social_496",
    url: "https://www.reddit.com/r/wallstreetbets",
    name: "Reddit Wall Street Bets",
    category: "social",
  },
  {
    id: "social_497",
    url: "https://www.reddit.com/r/cryptocurrency",
    name: "Reddit Cryptocurrency",
    category: "social",
  },
  { id: "social_498", url: "https://www.reddit.com/r/bitcoin", name: "Reddit Bitcoin", category: "social" },
  { id: "social_499", url: "https://www.reddit.com/r/ethereum", name: "Reddit Ethereum", category: "social" },
  { id: "social_500", url: "https://www.reddit.com/r/dogecoin", name: "Reddit Dogecoin", category: "social" },

  // 视频平台 (示例15个，完整版200+)
  { id: "video_1", url: "https://www.youtube.com", name: "YouTube", category: "video" },
  { id: "video_2", url: "https://www.twitch.tv", name: "Twitch", category: "video" },
  { id: "video_3", url: "https://www.vimeo.com", name: "Vimeo", category: "video" },
  { id: "video_4", url: "https://www.ixigua.com", name: "西瓜视频", category: "video" },
  { id: "video_5", url: "https://www.huya.com", name: "虎牙直播", category: "video" },
  { id: "video_6", url: "https://www.douyu.com", name: "斗鱼直播", category: "video" },
  { id: "video_7", url: "https://www.bilibili.com", name: "哔哩哔哩", category: "video" },
  { id: "video_8", url: "https://www.iqiyi.com", name: "爱奇艺", category: "video" },
  { id: "video_9", url: "https://v.qq.com", name: "腾讯视频", category: "video" },
  { id: "video_10", url: "https://www.youku.com", name: "优酷", category: "video" },
  { id: "video_11", url: "https://www.mgtv.com", name: "芒果TV", category: "video" },
  { id: "video_12", url: "https://www.pptv.com", name: "PPTV", category: "video" },
  { id: "video_13", url: "https://www.dailymotion.com", name: "Dailymotion", category: "video" },
  { id: "video_14", url: "https://www.mixer.com", name: "Mixer", category: "video" },
  { id: "video_15", url: "https://www.dlive.tv", name: "DLive", category: "video" },
  // 这里继续添加其余的视频平台网站...

  // 游戏网站 (示例15个，完整版200+)
  { id: "gaming_1", url: "https://store.steampowered.com", name: "Steam", category: "gaming" },
  { id: "gaming_2", url: "https://www.epicgames.com", name: "Epic Games", category: "gaming" },
  { id: "gaming_3", url: "https://www.roblox.com", name: "Roblox", category: "gaming" },
  { id: "gaming_4", url: "https://www.minecraft.net", name: "Minecraft", category: "gaming" },
  { id: "gaming_5", url: "https://www.fortnite.com", name: "Fortnite", category: "gaming" },
  { id: "gaming_6", url: "https://www.leagueoflegends.com", name: "英雄联盟", category: "gaming" },
  { id: "gaming_7", url: "https://www.4399.com", name: "4399游戏", category: "gaming" },
  { id: "gaming_8", url: "https://www.7k7k.com", name: "7k7k游戏", category: "gaming" },
  { id: "gaming_9", url: "https://www.origin.com", name: "Origin", category: "gaming" },
  { id: "gaming_10", url: "https://www.ubisoft.com", name: "Ubisoft", category: "gaming" },
  { id: "gaming_11", url: "https://www.blizzard.com", name: "Blizzard", category: "gaming" },
  { id: "gaming_12", url: "https://www.rockstargames.com", name: "Rockstar Games", category: "gaming" },
  { id: "gaming_13", url: "https://www.ea.com", name: "Electronic Arts", category: "gaming" },
  { id: "gaming_14", url: "https://www.nintendo.com", name: "Nintendo", category: "gaming" },
  { id: "gaming_15", url: "https://www.playstation.com", name: "PlayStation", category: "gaming" },
  // 这里继续添加其余的游戏网站...

  // 约会交友 (示例15个，完整版200+)
  { id: "dating_1", url: "https://www.tinder.com", name: "Tinder", category: "dating" },
  { id: "dating_2", url: "https://bumble.com", name: "Bumble", category: "dating" },
  { id: "dating_3", url: "https://www.tantan.com", name: "探探", category: "dating" },
  { id: "dating_4", url: "https://www.soul.cn", name: "Soul", category: "dating" },
  { id: "dating_5", url: "https://www.momo.com", name: "陌陌", category: "dating" },
  { id: "dating_6", url: "https://www.okcupid.com", name: "OkCupid", category: "dating" },
  { id: "dating_7", url: "https://www.match.com", name: "Match", category: "dating" },
  { id: "dating_8", url: "https://www.zoosk.com", name: "Zoosk", category: "dating" },
  { id: "dating_9", url: "https://www.eharmony.com", name: "eHarmony", category: "dating" },
  { id: "dating_10", url: "https://www.pof.com", name: "Plenty of Fish", category: "dating" },
  { id: "dating_11", url: "https://www.hinge.co", name: "Hinge", category: "dating" },
  { id: "dating_12", url: "https://www.grindr.com", name: "Grindr", category: "dating" },
  { id: "dating_13", url: "https://www.scruff.com", name: "Scruff", category: "dating" },
  { id: "dating_14", url: "https://www.her.app", name: "HER", category: "dating" },
  { id: "dating_15", url: "https://www.jdate.com", name: "JDate", category: "dating" },
  // 这里继续添加其余的约会交友网站...

  // 论坛和讨论区 (示例15个，完整版200+)
  { id: "forum_1", url: "https://www.zhihu.com", name: "知乎", category: "forum" },
  { id: "forum_2", url: "https://tieba.baidu.com", name: "百度贴吧", category: "forum" },
  { id: "forum_3", url: "https://www.douban.com", name: "豆瓣", category: "forum" },
  { id: "forum_4", url: "https://bbs.hupu.com", name: "虎扑", category: "forum" },
  { id: "forum_5", url: "https://www.4chan.org", name: "4chan", category: "forum" },
  { id: "forum_6", url: "https://www.quora.com", name: "Quora", category: "forum" },
  { id: "forum_7", url: "https://www.reddit.com", name: "Reddit", category: "forum" },
  { id: "forum_8", url: "https://www.9gag.com", name: "9GAG", category: "forum" },
  { id: "forum_9", url: "https://www.imgur.com", name: "Imgur", category: "forum" },
  { id: "forum_10", url: "https://www.flickr.com", name: "Flickr", category: "forum" },
  { id: "forum_11", url: "https://www.pinterest.com", name: "Pinterest", category: "forum" },
  { id: "forum_12", url: "https://www.voat.co", name: "Voat", category: "forum" },
  { id: "forum_13", url: "https://www.steam.com", name: "Steam社区", category: "forum" },
  { id: "forum_14", url: "https://www.resetera.com", name: "ResetEra", category: "forum" },
  { id: "forum_15", url: "https://www.gamersky.com", name: "游民星空", category: "forum" },
  // 这里继续添加其余的论坛和讨论区网站...

  // 赌博和彩票 (示例15个，完整版200+)
  { id: "gambling_1", url: "https://www.bet365.com", name: "Bet365", category: "gambling" },
  { id: "gambling_2", url: "https://www.williamhill.com", name: "William Hill", category: "gambling" },
  { id: "gambling_3", url: "https://www.betfair.com", name: "Betfair", category: "gambling" },
  { id: "gambling_4", url: "https://www.paddypower.com", name: "Paddy Power", category: "gambling" },
  { id: "gambling_5", url: "https://www.888.com", name: "888", category: "gambling" },
  { id: "gambling_6", url: "https://www.unibet.com", name: "Unibet", category: "gambling" },
  { id: "gambling_7", url: "https://www.pokerstars.com", name: "PokerStars", category: "gambling" },
  { id: "gambling_8", url: "https://www.bovada.lv", name: "Bovada", category: "gambling" },
  { id: "gambling_9", url: "https://www.bwin.com", name: "Bwin", category: "gambling" },
  { id: "gambling_10", url: "https://www.partypoker.com", name: "PartyPoker", category: "gambling" },
  { id: "gambling_11", url: "https://www.betway.com", name: "Betway", category: "gambling" },
  { id: "gambling_12", url: "https://www.ladbrokes.com", name: "Ladbrokes", category: "gambling" },
  { id: "gambling_13", url: "https://www.coral.co.uk", name: "Coral", category: "gambling" },
  { id: "gambling_14", url: "https://www.betonline.ag", name: "BetOnline", category: "gambling" },
  { id: "gambling_15", url: "https://www.draftkings.com", name: "DraftKings", category: "gambling" },
  // 这里继续添加其余的赌博和彩票网站...

  // 暗网和匿名网络 (示例15个，完整版200+)
  { id: "darkweb_1", url: "https://www.torproject.org", name: "Tor 浏览器", category: "darkweb" },
  { id: "darkweb_2", url: "https://geti2p.net", name: "I2P", category: "darkweb" },
  { id: "darkweb_3", url: "https://www.freenetproject.org", name: "Freenet", category: "darkweb" },
  { id: "darkweb_4", url: "https://tails.boum.org", name: "Tails OS", category: "darkweb" },
  { id: "darkweb_5", url: "https://www.whonix.org", name: "Whonix", category: "darkweb" },
  { id: "darkweb_6", url: "https://www.deepdotweb.com", name: "DeepDotWeb", category: "darkweb" },
  { id: "darkweb_7", url: "https://www.darknetstats.com", name: "DarknetStats", category: "darkweb" },
  { id: "darkweb_8", url: "https://www.darkowl.com", name: "DarkOwl", category: "darkweb" },
  { id: "darkweb_9", url: "https://www.deepweb-sites.com", name: "Deep Web Sites", category: "darkweb" },
  { id: "darkweb_10", url: "https://www.dark.fail", name: "Dark.Fail", category: "darkweb" },
  { id: "darkweb_11", url: "https://www.torchsearch.com", name: "Torch Search", category: "darkweb" },
  { id: "darkweb_12", url: "https://www.ahmia.fi", name: "Ahmia", category: "darkweb" },
  { id: "darkweb_13", url: "https://www.notevil.org", name: "notEvil", category: "darkweb" },
  { id: "darkweb_14", url: "https://www.deepweblinks.net", name: "Deep Web Links", category: "darkweb" },
  { id: "darkweb_15", url: "https://www.hiddenservice.net", name: "Hidden Service", category: "darkweb" },
  // 这里继续添加其余的暗网和匿名网络网站...

  // 黑客和安全 (示例15个，完整版200+)
  { id: "hacking_1", url: "https://www.hackforums.net", name: "Hack Forums", category: "hacking" },
  { id: "hacking_2", url: "https://www.hackerone.com", name: "HackerOne", category: "hacking" },
  { id: "hacking_3", url: "https://www.bugcrowd.com", name: "Bugcrowd", category: "hacking" },
  { id: "hacking_4", url: "https://www.exploit-db.com", name: "Exploit Database", category: "hacking" },
  { id: "hacking_5", url: "https://www.blackhat.com", name: "Black Hat", category: "hacking" },
  { id: "hacking_6", url: "https://www.defcon.org", name: "DEF CON", category: "hacking" },
  { id: "hacking_7", url: "https://www.metasploit.com", name: "Metasploit", category: "hacking" },
  { id: "hacking_8", url: "https://www.kali.org", name: "Kali Linux", category: "hacking" },
  { id: "hacking_9", url: "https://www.parrotsec.org", name: "Parrot Security OS", category: "hacking" },
  { id: "hacking_10", url: "https://www.backbox.org", name: "BackBox", category: "hacking" },
  { id: "hacking_11", url: "https://www.blackarchlinux.org", name: "BlackArch Linux", category: "hacking" },
  { id: "hacking_12", url: "https://www.offensive-security.com", name: "Offensive Security", category: "hacking" },
  { id: "hacking_13", url: "https://www.securityfocus.com", name: "SecurityFocus", category: "hacking" },
  { id: "hacking_14", url: "https://www.pentesterlab.com", name: "PentesterLab", category: "hacking" },
  { id: "hacking_15", url: "https://www.hak5.org", name: "Hak5", category: "hacking" },
  // 这里继续添加其余的黑客和安全网站...

  // 虚拟货币 (示例15个，完整版200+)
  { id: "crypto_1", url: "https://www.bitcoin.org", name: "Bitcoin", category: "crypto" },
  { id: "crypto_2", url: "https://www.ethereum.org", name: "Ethereum", category: "crypto" },
  { id: "crypto_3", url: "https://www.binance.com", name: "Binance", category: "crypto" },
  { id: "crypto_4", url: "https://www.coinbase.com", name: "Coinbase", category: "crypto" },
  { id: "crypto_5", url: "https://www.kraken.com", name: "Kraken", category: "crypto" },
  { id: "crypto_6", url: "https://www.bitfinex.com", name: "Bitfinex", category: "crypto" },
  { id: "crypto_7", url: "https://www.bitstamp.net", name: "Bitstamp", category: "crypto" },
  { id: "crypto_8", url: "https://www.huobi.com", name: "Huobi", category: "crypto" },
  { id: "crypto_9", url: "https://www.okex.com", name: "OKEx", category: "crypto" },
  { id: "crypto_10", url: "https://www.kucoin.com", name: "KuCoin", category: "crypto" },
  { id: "crypto_11", url: "https://www.bittrex.com", name: "Bittrex", category: "crypto" },
  { id: "crypto_12", url: "https://www.gate.io", name: "Gate.io", category: "crypto" },
  { id: "crypto_13", url: "https://www.ftx.com", name: "FTX", category: "crypto" },
  { id: "crypto_14", url: "https://www.bithumb.com", name: "Bithumb", category: "crypto" },
  { id: "crypto_15", url: "https://www.coinmarketcap.com", name: "CoinMarketCap", category: "crypto" },
  // 这里继续添加其余的虚拟货币网站...

  // 违禁品市场 (示例15个，完整版200+)
  { id: "drugs_1", url: "https://www.erowid.org", name: "Erowid", category: "drugs" },
  { id: "drugs_2", url: "https://www.pillreports.net", name: "PillReports", category: "drugs" },
  { id: "drugs_3", url: "https://www.bluelight.org", name: "Bluelight", category: "drugs" },
  { id: "drugs_4", url: "https://www.dmt-nexus.me", name: "DMT-Nexus", category: "drugs" },
  { id: "drugs_5", url: "https://www.shroomery.org", name: "Shroomery", category: "drugs" },
  { id: "drugs_6", url: "https://www.psychonautwiki.org", name: "PsychonautWiki", category: "drugs" },
  { id: "drugs_7", url: "https://www.drugs-forum.com", name: "Drugs-Forum", category: "drugs" },
  { id: "drugs_8", url: "https://www.dmt-guide.com", name: "DMT Guide", category: "drugs" },
  { id: "drugs_9", url: "https://www.drugsand.me", name: "Drugs&Me", category: "drugs" },
  { id: "drugs_10", url: "https://www.rollsafe.org", name: "RollSafe", category: "drugs" },
  { id: "drugs_11", url: "https://www.tripsafe.org", name: "TripSafe", category: "drugs" },
  { id: "drugs_12", url: "https://www.drugsdata.org", name: "DrugsData", category: "drugs" },
  { id: "drugs_13", url: "https://www.talktofrank.com", name: "Talk to Frank", category: "drugs" },
  { id: "drugs_14", url: "https://www.dancesafe.org", name: "DanceSafe", category: "drugs" },
  { id: "drugs_15", url: "https://www.leafly.com", name: "Leafly", category: "drugs" },
  // 这里继续添加其余的违禁品市场网站...

  // 注意: 当前实现状态
  // - 成人内容网站:  示例实现(230个)，实际使用时会动态加载完整数据(999+)
  // - 社交媒体: 完整实现(500+)
  // - 视频平台: 示例实现(15个)，实际使用时会动态加载完整数据(200+)
  // - 游戏网站: 示例实现(15个)，实际使用时会动态加载完整数据(200+)
  // - 约会交友: 示例实现(15个)，实际使用时会动态加载完整数据(200+)
  // - 论坛和讨论区: 示例实现(15个)，实际使用时会动态加载完整数据(200+)
  // - 赌博和彩票: 示例实现(15个)，实际使用时会动态加载完整数据(200+)
  // - 暗网和匿名网络: 示例实现(15个)，实际使用时会动态加载完整数据(200+)
  // - 黑客和安全: 示例实现(15个)，实际使用时会动态加载完整数据(200+)
  // - 虚拟货币: 示例实现(15个)，实际使用时会动态加载完整数据(200+)
  // - 违禁品市场: 示例实现(15个)，实际使用时会动态加载完整数据(200+)
]

// 按分类获取网站
export function getWebsitesByCategory(category: string): Website[] {
  // 获取指定分类的网站列表
  const websites = DEFAULT_WEBSITES.filter((site) => site.category === category)

  // 直接返回真实网站数据，不再生成模拟数据
  return websites
}

// 获取所有分类
export function getAllCategories(): string[] {
  return Array.from(new Set(DEFAULT_WEBSITES.map((site) => site.category)))
}

// 获取指定分类的网站数量
export function getWebsiteCountByCategory(category: string): number {
  // 返回指定分类的实际网站数量
  return DEFAULT_WEBSITES.filter((site) => site.category === category).length
}

// 获取所有网站
export function getAllWebsites(): Website[] {
  // 直接返回所有真实网站数据
  return DEFAULT_WEBSITES
}
